/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elxect;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.border.Border;

/**
 *
 * @author Lenovo
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    
    Connection conn;
    Statement stmt; 
    
    public AdminHome() {
        initComponents();
        filluserCombo(userCombo);
        filluserCombometer(userCombo1);
        filluserCombometer(jComboBox1);
        adminNameField.setBackground(new Color(0,0,0,1));
        adminpasswordField.setBackground(new Color(0,0,0,1));
        conadminpasswordField.setBackground(new Color(0,0,0,1));
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        userDetailsButton.setBorder(border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void connection(){
        try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electrify", "sam", "sam22");
        stmt = conn.createStatement();
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
   public void setGenerateBill(String user){
        String tmpname;
        String tmpmeterno = user;
        String tmpmetertype;
        String tmpmonth;
        String tmpunit;
        String tmpbilltype;
        String tmpservice;
        String tmpgst;
        String tmpamount; 
        String gg = "2222";
        connection();
        
        try{
        String sql = "select name from main where meter_number = '"+tmpmeterno+"'";
        ResultSet r = stmt.executeQuery(sql);
        AdminHome.gbmeterField.setText(tmpmeterno);
        while(r.next()){
        tmpname = r.getString("name");
        AdminHome.gbnameField.setText(tmpname);
        
        }
        String upsql = "select * from billsbymonth where meter_number = '"+tmpmeterno+"'";
        ResultSet rs = stmt.executeQuery(upsql);
        AdminHome.gbmonthField.setText("January");
        while(rs.next()){
         tmpmonth = rs.getString("january");
         
         AdminHome.gbamountField.setText(tmpmonth);
         gg = tmpmonth;
        }
         
        
        String upsql2 = "select * from unitsbymonth where meter_number = '"+tmpmeterno+"'";
                    ResultSet rs1 = stmt.executeQuery(upsql2);
                    while(rs1.next())
                    {
                        tmpunit  = rs1.getString("january");
                        AdminHome.gbunitField.setText(tmpunit);
                    }
                    
        String sql1s = "select * from meterdetails where meter_number = '"+tmpmeterno+"'";
        ResultSet rs1s = stmt.executeQuery(sql1s);
        while(rs1s.next()){
         tmpmetertype = rs1s.getString("meter_type");
         AdminHome.gbmetertypeField.setText(tmpmetertype);
         tmpbilltype = rs1s.getString("bill_type");
         AdminHome.gbbilltypeField.setText(tmpbilltype);
         tmpservice  = rs1s.getString("service_rent");
         AdminHome.gbserviceField.setText(tmpservice);
         
         
        }
        tmpgst = String.valueOf(Integer.parseInt(gg) * 9 / 100);
        AdminHome.gbgstField.setText(tmpgst);
        JOptionPane.showMessageDialog(this, "updated");
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
   
   
   public void setMeterDetails(String meter){
        String tmpname;
        String tmpmeterno = meter;
        String tmpmetertype;
        String tmpphase;
        String tmpregion;
        String tmpmcb;
        connection();
        
        try{
        String sql = "select * from main where meter_number = '"+tmpmeterno+"'";
        ResultSet r = stmt.executeQuery(sql);
        
        while(r.next()){
        tmpname = r.getString("name");
        AdminHome.nameField.setText(tmpname);
        tmpregion = r.getString("address");
        AdminHome.mdreigonField.setText(tmpregion);
        }
        String upsql = "select * from meterdetails where meter_number = '"+tmpmeterno+"'";
        ResultSet rs = stmt.executeQuery(upsql);
        
        while(rs.next()){
         
         AdminHome.mdmeterField.setText(tmpmeterno);
         tmpmetertype = rs.getString("meter_type");
         AdminHome.mdmetertypeField.setText(tmpmetertype);
         tmpphase  = rs.getString("phase_code");
         AdminHome.mdphaseField.setText(tmpphase);
         tmpmcb = rs.getString("mcb_rent");
         AdminHome.mdmcbField.setText(tmpmcb);
        }
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    } 
    
    public void filluserCombometer(JComboBox box){

                                try{
                                    
                                    connection();
                                    String sql = "select * from main";
                                    ResultSet rs = stmt.executeQuery(sql);
                                    while(rs.next())
                                    {
                                    String tmpname = rs.getString("meter_number");
                                    box.addItem(tmpname);
                                    
                                    }
                                    
                                    }
                                catch(Exception ex){
                                
                                                    JOptionPane.showMessageDialog(this, ex.getMessage());
                                                    }
                                }
    
    public void filluserCombo(JComboBox box){

                                try{
                                    
                                    connection();
                                    String sql = "select * from newuser";
                                    ResultSet rs = stmt.executeQuery(sql);
                                    while(rs.next())
                                    {
                                    String tmpname = rs.getString("name");
                                    box.addItem(tmpname);
                                    
                                    }
                                    
                                    }
                                catch(Exception ex){
                                
                                                    JOptionPane.showMessageDialog(this, ex.getMessage());
                                                    }
                                }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        createNewAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userDetailsButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generateBillButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JLabel();
        adminpanelLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        topstripLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        userDetailsPanel = new javax.swing.JPanel();
        userCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        meterLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        billLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        metertypeLabel = new javax.swing.JLabel();
        phasecodeLabel = new javax.swing.JLabel();
        createAdminPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adminNameField = new javax.swing.JTextField();
        adminpasswordField = new javax.swing.JPasswordField();
        conadminpasswordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        meterReadingLabel = new javax.swing.JPanel();
        userCombo1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        mdmeterField = new javax.swing.JTextField();
        mdmetertypeField = new javax.swing.JTextField();
        mdreigonField = new javax.swing.JTextField();
        mdmcbField = new javax.swing.JTextField();
        mdphaseField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        generateBillPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        gbnameField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gbmeterField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        gbmetertypeField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        gbmonthField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        gbunitField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        gbbilltypeField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        gbserviceField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        gbgstField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        gbamountField = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create Admin");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(760, 90, 130, 20);

        createNewAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminbutton.png"))); // NOI18N
        createNewAdmin.setText("jLabel1");
        createNewAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createNewAdminMouseClicked(evt);
            }
        });
        jPanel2.add(createNewAdmin);
        createNewAdmin.setBounds(730, 80, 185, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Details");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 90, 110, 20);

        userDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminbutton.png"))); // NOI18N
        userDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDetailsButtonMouseClicked(evt);
            }
        });
        jPanel2.add(userDetailsButton);
        userDetailsButton.setBounds(20, 80, 185, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Generate Bill");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 90, 120, 20);

        generateBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminbutton.png"))); // NOI18N
        generateBillButton.setText("jLabel1");
        generateBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseClicked(evt);
            }
        });
        jPanel2.add(generateBillButton);
        generateBillButton.setBounds(250, 80, 185, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meter Reading");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(520, 90, 150, 20);

        deleteUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminbutton.png"))); // NOI18N
        deleteUserButton.setText("jLabel1");
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserButtonMouseClicked(evt);
            }
        });
        jPanel2.add(deleteUserButton);
        deleteUserButton.setBounds(500, 80, 185, 40);

        adminpanelLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminpanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminpanelLabel.setText("Admin Panel");
        jPanel2.add(adminpanelLabel);
        adminpanelLabel.setBounds(400, 20, 150, 30);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logg.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel28);
        jLabel28.setBounds(880, 10, 50, 40);

        topstripLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminTop.png"))); // NOI18N
        jPanel2.add(topstripLabel);
        topstripLabel.setBounds(0, 0, 940, 70);

        bottomPanel.setLayout(new java.awt.CardLayout());

        userDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        userDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 204)));

        userCombo.setOpaque(false);

        jButton1.setText("Get Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mobile");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Meter No");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("City");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Bill Amount");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Unit Consumed");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Meter Type");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Phase code");

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mobileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        meterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        billLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        metertypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        phasecodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout userDetailsPanelLayout = new javax.swing.GroupLayout(userDetailsPanel);
        userDetailsPanel.setLayout(userDetailsPanelLayout);
        userDetailsPanelLayout.setHorizontalGroup(
            userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(metertypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phasecodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );
        userDetailsPanelLayout.setVerticalGroup(
            userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(meterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metertypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phasecodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        bottomPanel.add(userDetailsPanel, "card2");

        createAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        createAdminPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createAdminPanel.setForeground(new java.awt.Color(153, 0, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Admin Name");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Password");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Confirm Password");

        adminNameField.setBackground(null);
        adminNameField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        adminpasswordField.setBackground(null);
        adminpasswordField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminpasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        conadminpasswordField.setBackground(null);
        conadminpasswordField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        conadminpasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Create");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 4, 80, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createButton.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 100, 25);

        javax.swing.GroupLayout createAdminPanelLayout = new javax.swing.GroupLayout(createAdminPanel);
        createAdminPanel.setLayout(createAdminPanelLayout);
        createAdminPanelLayout.setHorizontalGroup(
            createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAdminPanelLayout.createSequentialGroup()
                .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAdminPanelLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conadminpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createAdminPanelLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        createAdminPanelLayout.setVerticalGroup(
            createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAdminPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(createAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conadminpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        bottomPanel.add(createAdminPanel, "card5");

        meterReadingLabel.setBackground(new java.awt.Color(255, 255, 255));
        meterReadingLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255)));

        userCombo1.setOpaque(false);
        userCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCombo1ActionPerformed(evt);
            }
        });

        jButton3.setText("Get Meter Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        mdmeterField.setEditable(false);
        mdmeterField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mdmeterField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdmetertypeField.setEditable(false);
        mdmetertypeField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mdmetertypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdreigonField.setEditable(false);
        mdreigonField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mdreigonField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdmcbField.setEditable(false);
        mdmcbField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mdmcbField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdphaseField.setEditable(false);
        mdphaseField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mdphaseField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Meter No");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Meter Type");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Location");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("mcb rent");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("phase");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Name");

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout meterReadingLabelLayout = new javax.swing.GroupLayout(meterReadingLabel);
        meterReadingLabel.setLayout(meterReadingLabelLayout);
        meterReadingLabelLayout.setHorizontalGroup(
            meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, meterReadingLabelLayout.createSequentialGroup()
                .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meterReadingLabelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(userCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(meterReadingLabelLayout.createSequentialGroup()
                        .addContainerGap(262, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)))
                .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mdmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(meterReadingLabelLayout.createSequentialGroup()
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdphaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, meterReadingLabelLayout.createSequentialGroup()
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdmcbField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, meterReadingLabelLayout.createSequentialGroup()
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdreigonField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, meterReadingLabelLayout.createSequentialGroup()
                            .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66)
                            .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mdmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(167, 167, 167))
        );
        meterReadingLabelLayout.setVerticalGroup(
            meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterReadingLabelLayout.createSequentialGroup()
                .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meterReadingLabelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(meterReadingLabelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(28, 28, 28)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(28, 28, 28)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdreigonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(28, 28, 28)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdmcbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(28, 28, 28)
                        .addGroup(meterReadingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mdphaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        bottomPanel.add(meterReadingLabel, "card4");

        generateBillPanel.setBackground(new java.awt.Color(255, 255, 255));
        generateBillPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255)));

        jButton2.setText("Generate Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Name");

        gbnameField.setEditable(false);
        gbnameField.setBackground(new java.awt.Color(255, 255, 255));
        gbnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Meter No");

        gbmeterField.setEditable(false);
        gbmeterField.setBackground(new java.awt.Color(255, 255, 255));
        gbmeterField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Meter type");

        gbmetertypeField.setEditable(false);
        gbmetertypeField.setBackground(new java.awt.Color(255, 255, 255));
        gbmetertypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Month");

        gbmonthField.setEditable(false);
        gbmonthField.setBackground(new java.awt.Color(255, 255, 255));
        gbmonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Units");

        gbunitField.setEditable(false);
        gbunitField.setBackground(new java.awt.Color(255, 255, 255));
        gbunitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Bill type");

        gbbilltypeField.setEditable(false);
        gbbilltypeField.setBackground(new java.awt.Color(255, 255, 255));
        gbbilltypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Service Charge");

        gbserviceField.setEditable(false);
        gbserviceField.setBackground(new java.awt.Color(255, 255, 255));
        gbserviceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("GST 9%");

        gbgstField.setEditable(false);
        gbgstField.setBackground(new java.awt.Color(255, 255, 255));
        gbgstField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Amount");

        gbamountField.setEditable(false);
        gbamountField.setBackground(new java.awt.Color(255, 255, 255));
        gbamountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout generateBillPanelLayout = new javax.swing.GroupLayout(generateBillPanel);
        generateBillPanel.setLayout(generateBillPanelLayout);
        generateBillPanelLayout.setHorizontalGroup(
            generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBillPanelLayout.createSequentialGroup()
                .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generateBillPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gbmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(generateBillPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28)
                                .addComponent(gbnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140)
                .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbunitField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbbilltypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(32, 32, 32)
                            .addComponent(gbserviceField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbgstField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(generateBillPanelLayout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printButton)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        generateBillPanelLayout.setVerticalGroup(
            generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBillPanelLayout.createSequentialGroup()
                .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(gbmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(gbmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(gbunitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(gbbilltypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(gbserviceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jComboBox2))
                        .addGap(59, 59, 59)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(gbnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(gbmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(generateBillPanelLayout.createSequentialGroup()
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(gbgstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(generateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(gbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(printButton)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        bottomPanel.add(generateBillPanel, "card3");

        jPanel2.add(bottomPanel);
        bottomPanel.setBounds(0, 130, 940, 414);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetailsButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        userDetailsButton.setBorder(border);
        generateBillButton.setBorder(empty);
        deleteUserButton.setBorder(empty);
        createNewAdmin.setBorder(empty);
        
        userDetailsPanel.setVisible(true);
        generateBillPanel.setVisible(false);
        meterReadingLabel.setVisible(false);
        createAdminPanel.setVisible(false);
        
        
    }//GEN-LAST:event_userDetailsButtonMouseClicked

    private void generateBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        userDetailsButton.setBorder(empty);
        generateBillButton.setBorder(border);
        deleteUserButton.setBorder(empty);
        createNewAdmin.setBorder(empty);
        userDetailsPanel.setVisible(false);
        generateBillPanel.setVisible(true);
        meterReadingLabel.setVisible(false);
        createAdminPanel.setVisible(false);
    }//GEN-LAST:event_generateBillButtonMouseClicked

    private void deleteUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        userDetailsButton.setBorder(empty);
        generateBillButton.setBorder(empty);
        deleteUserButton.setBorder(border);
        createNewAdmin.setBorder(empty);
        userDetailsPanel.setVisible(false);
        generateBillPanel.setVisible(false);
        meterReadingLabel.setVisible(true);
        createAdminPanel.setVisible(false);
    }//GEN-LAST:event_deleteUserButtonMouseClicked

    private void createNewAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewAdminMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        userDetailsButton.setBorder(empty);
        generateBillButton.setBorder(empty);
        deleteUserButton.setBorder(empty);
        createNewAdmin.setBorder(border);
        userDetailsPanel.setVisible(false);
        generateBillPanel.setVisible(false);
        meterReadingLabel.setVisible(false);
        createAdminPanel.setVisible(true);
    }//GEN-LAST:event_createNewAdminMouseClicked
    
    
    public void createAdmin(){
            
            connection();
            try{
            String name =  adminNameField.getText();
            String pass = adminpasswordField.getText();
            String conpass = conadminpasswordField.getText();
            if(pass.equals(conpass)){
            String sql = "INSERT INTO admin " + "VALUES ('"+name+"', '"+pass+"')";
            int rs = stmt.executeUpdate(sql);
            if(rs == 0){
                
                this.dispose();
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Done Created New Admin");
                adminNameField.setText("");
                adminpasswordField.setText("");
                conadminpasswordField.setText("");
            }
            }
            else{
                    
                    JOptionPane.showMessageDialog(null,"Password Don't match");
                }
            }
            catch(Exception ex){
            
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
    
    
    }   

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        createAdmin();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Object o = userCombo.getSelectedItem();
        String user = o.toString();
        try{
                                    
            connection();
            String sql = "select * from main where name = '"+user+"'";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
            String tmpname = rs.getString("name");
            usernameLabel.setText(tmpname);
            String tmpemail = rs.getString("email");
            emailLabel.setText(tmpemail);
            String tmpmobile = rs.getString("phone");
            mobileLabel.setText(tmpmobile);
            String tmpmeter = rs.getString("meter_number");
            meterLabel.setText(tmpmeter);
            String tmpcity = rs.getString("city");
            cityLabel.setText(tmpcity);
            }    
            
            String sql2 = "select * from billsbymonth where meter_number = '"+meterLabel.getText()+"'";
            ResultSet rs2 = stmt.executeQuery(sql2);
            while(rs2.next()){
                
                String tmpbill = rs2.getString("october");
                billLabel.setText(tmpbill);
            }
            
            String sqll = "select * from unitsbymonth where meter_number = '"+meterLabel.getText()+"'";
            ResultSet rss2 = stmt.executeQuery(sqll);
            while(rss2.next()){
            String tmpunit = rss2.getString("october");
            unitLabel.setText(tmpunit);
            }
            
            String sql1 = "select * from meterdetails where meter_number = '"+meterLabel.getText()+"'";
            ResultSet rs1 = stmt.executeQuery(sql1);
            while(rs1.next()){
                
                String tmpmt = rs1.getString("meter_type");
                metertypeLabel.setText(tmpmt);
                String tmppc = rs1.getString("phase_code");
                phasecodeLabel.setText(tmppc);
            }
            
            
           }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
                           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCombo1ActionPerformed

    
    
    public void  setamountunit(String s1, String s2)
    {
            String meterno = s1;
            String month = s2;
            String meteramount;
            String meterunit;
            String tmpgst;
            String gg = "3333";
            
            try{
            connection();
            String sql = "select * from billsbymonth where meter_number = '"+meterno+"'";
            ResultSet r = stmt.executeQuery(sql);
            while(r.next())
            {
                
                
                gbmonthField.setText(s2);
                meteramount = r.getString(month);
                gbamountField.setText(meteramount);
                gg = meteramount;
                
            }
            
            String sql1 = "select * from unitsbymonth where meter_number = '"+meterno+"'";
            ResultSet rs = stmt.executeQuery(sql1);
            while(rs.next())
            {
                meterunit = rs.getString(month);
                gbunitField.setText(meterunit);
                
                
            }
            tmpgst = String.valueOf(Integer.parseInt(gg) * 9 / 100);
            AdminHome.gbgstField.setText(tmpgst);
            JOptionPane.showMessageDialog(this, "updated");
            }
            
            catch(Exception ex)
            {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
            
    }
    public void checkifchangegb(String s1, String s2)
    {
    String jan = "January";
    if(jan.equals(s2))
    {
            setGenerateBill(s1);
    }
    else
    {
            setamountunit(s1,s2);
    }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object o = jComboBox1.getSelectedItem();
        String s = o.toString();
        
        
        
        Object obj = jComboBox2.getSelectedItem();
        String ss = obj.toString();
        
        checkifchangegb(s,ss);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Object o = userCombo1.getSelectedItem();
        String s = o.toString();
        setMeterDetails(s);
            
           
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
     public void printComponenet(Component component){
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");
        pj.setPrintable (new Printable() {    
        @Override
        public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
            return Printable.NO_SUCH_PAGE;
      }

        Graphics2D g2 = (Graphics2D) pg;
        g2.translate(pf.getImageableX(), pf.getImageableY());
        component.paint(g2);
        return Printable.PAGE_EXISTS;
                                                                 }
                                         }
                        );
        if (pj.printDialog() == false)
            return;

        try {
                pj.print();
            } 
        catch (PrinterException ex) {
        // handle exception
                }
        }
     
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        printComponenet(generateBillPanel);

    }//GEN-LAST:event_printButtonActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SignIn().setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminNameField;
    private javax.swing.JLabel adminpanelLabel;
    private javax.swing.JPasswordField adminpasswordField;
    private javax.swing.JLabel billLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JPasswordField conadminpasswordField;
    private javax.swing.JPanel createAdminPanel;
    private javax.swing.JLabel createNewAdmin;
    private javax.swing.JLabel deleteUserButton;
    private javax.swing.JLabel emailLabel;
    public static javax.swing.JTextField gbamountField;
    public static javax.swing.JTextField gbbilltypeField;
    public static javax.swing.JTextField gbgstField;
    public static javax.swing.JTextField gbmeterField;
    public static javax.swing.JTextField gbmetertypeField;
    public static javax.swing.JTextField gbmonthField;
    public static javax.swing.JTextField gbnameField;
    public static javax.swing.JTextField gbserviceField;
    public static javax.swing.JTextField gbunitField;
    private javax.swing.JLabel generateBillButton;
    private javax.swing.JPanel generateBillPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField mdmcbField;
    public static javax.swing.JTextField mdmeterField;
    public static javax.swing.JTextField mdmetertypeField;
    public static javax.swing.JTextField mdphaseField;
    public static javax.swing.JTextField mdreigonField;
    private javax.swing.JLabel meterLabel;
    private javax.swing.JPanel meterReadingLabel;
    private javax.swing.JLabel metertypeLabel;
    private javax.swing.JLabel mobileLabel;
    public static javax.swing.JTextField nameField;
    private javax.swing.JLabel phasecodeLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel topstripLabel;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JComboBox<String> userCombo;
    private javax.swing.JComboBox<String> userCombo1;
    private javax.swing.JLabel userDetailsButton;
    private javax.swing.JPanel userDetailsPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
