/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elxect;

import java.sql.Statement;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;

/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Connection conn;
    Statement stmt;
    
    public Home() {
        initComponents();
        versionLabel.setText("");
        thanksLabel.setText("");
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        myProfileButton.setBorder(border );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void connection(){
        try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electrify", "sam", "sam22");
        stmt = conn.createStatement();
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seondCore = new javax.swing.JPanel();
        logoutButton = new javax.swing.JLabel();
        infoButton = new javax.swing.JLabel();
        settingButton = new javax.swing.JLabel();
        rightBackground = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mpNameField = new javax.swing.JTextField();
        mpEmailField = new javax.swing.JTextField();
        mpMobField = new javax.swing.JTextField();
        mpAddField = new javax.swing.JTextField();
        mpMeterField = new javax.swing.JTextField();
        mpStateField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbmeterNoField = new javax.swing.JTextField();
        cbmonthField = new javax.swing.JTextField();
        cbunitField = new javax.swing.JTextField();
        cbamountField = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        gbserviceField = new javax.swing.JTextField();
        gbnameField = new javax.swing.JTextField();
        gbmeterField = new javax.swing.JTextField();
        gbmetertypeField = new javax.swing.JTextField();
        gbunitField = new javax.swing.JTextField();
        gbbilltypeField = new javax.swing.JTextField();
        gbgstField = new javax.swing.JTextField();
        gbamountField = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        gbmonthField = new javax.swing.JComboBox<>();
        updatemonth = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        mdmeterField = new javax.swing.JTextField();
        mdmetertypeField = new javax.swing.JTextField();
        mdphaseField = new javax.swing.JTextField();
        mdreigonField = new javax.swing.JTextField();
        mdmcbField = new javax.swing.JTextField();
        panel5 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cardField = new javax.swing.JTextField();
        expmntField = new javax.swing.JTextField();
        expyrField = new javax.swing.JTextField();
        cvvField = new javax.swing.JTextField();
        payamountField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        payBillButton = new javax.swing.JLabel();
        myProfileButton = new javax.swing.JLabel();
        currentBillButton = new javax.swing.JLabel();
        generateBillButton = new javax.swing.JLabel();
        meterdetailsButton = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        thanksLabel = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        seondCore.setPreferredSize(new java.awt.Dimension(940, 544));
        seondCore.setLayout(null);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutButton.png"))); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        seondCore.add(logoutButton);
        logoutButton.setBounds(200, 470, 40, 40);

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutUsButton.png"))); // NOI18N
        infoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoButtonMouseExited(evt);
            }
        });
        seondCore.add(infoButton);
        infoButton.setBounds(130, 470, 40, 40);

        settingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settingButton.png"))); // NOI18N
        settingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingButtonMouseExited(evt);
            }
        });
        seondCore.add(settingButton);
        settingButton.setBounds(60, 470, 40, 40);

        rightBackground.setPreferredSize(new java.awt.Dimension(640, 544));
        rightBackground.setLayout(new java.awt.CardLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(640, 545));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mobile");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Meter No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("State");

        mpNameField.setEditable(false);
        mpNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpEmailField.setEditable(false);
        mpEmailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpMobField.setEditable(false);
        mpMobField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpAddField.setEditable(false);
        mpAddField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpMeterField.setEditable(false);
        mpMeterField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpStateField.setEditable(false);
        mpStateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("My Profile");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mpStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mpAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mpMeterField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mpMobField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mpEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mpNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(377, 377, 377)))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(256, 256, 256))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mpNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mpEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mpMobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mpAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mpMeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mpStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        rightBackground.add(panel1, "card2");

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setPreferredSize(new java.awt.Dimension(640, 544));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Current Bill");

        jLabel9.setText("Meter No");

        jLabel10.setText("Month");

        jLabel11.setText("Units Consumed");

        jLabel12.setText("Amount");

        cbmeterNoField.setEditable(false);
        cbmeterNoField.setBackground(new java.awt.Color(255, 255, 255));
        cbmeterNoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbmonthField.setEditable(false);
        cbmonthField.setBackground(new java.awt.Color(255, 255, 255));
        cbmonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cbmonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonthFieldActionPerformed(evt);
            }
        });

        cbunitField.setEditable(false);
        cbunitField.setBackground(new java.awt.Color(255, 255, 255));
        cbunitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbamountField.setEditable(false);
        cbamountField.setBackground(new java.awt.Color(255, 255, 255));
        cbamountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(69, 69, 69)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbunitField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmeterNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel8)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbmeterNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbunitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        rightBackground.add(panel2, "card3");

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        panel3.setPreferredSize(new java.awt.Dimension(640, 544));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Generated Bill");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upstripLabel.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sideStripLabel.png"))); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sideStripLabel.png"))); // NOI18N
        jLabel16.setText("jLabel15");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Name");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Meter No");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Meter type");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Month");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Units");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Bill type");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Service Charge");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("GST 9%");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Amount");

        gbserviceField.setEditable(false);
        gbserviceField.setBackground(new java.awt.Color(255, 255, 255));
        gbserviceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbnameField.setEditable(false);
        gbnameField.setBackground(new java.awt.Color(255, 255, 255));
        gbnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbmeterField.setEditable(false);
        gbmeterField.setBackground(new java.awt.Color(255, 255, 255));
        gbmeterField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbmetertypeField.setEditable(false);
        gbmetertypeField.setBackground(new java.awt.Color(255, 255, 255));
        gbmetertypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbunitField.setEditable(false);
        gbunitField.setBackground(new java.awt.Color(255, 255, 255));
        gbunitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbbilltypeField.setEditable(false);
        gbbilltypeField.setBackground(new java.awt.Color(255, 255, 255));
        gbbilltypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbgstField.setEditable(false);
        gbgstField.setBackground(new java.awt.Color(255, 255, 255));
        gbgstField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gbamountField.setEditable(false);
        gbamountField.setBackground(new java.awt.Color(255, 255, 255));
        gbamountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        gbmonthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        gbmonthField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gbmonthFieldMouseClicked(evt);
            }
        });

        updatemonth.setText("update");
        updatemonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbbilltypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(32, 32, 32)
                                .addComponent(gbserviceField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbgstField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gbunitField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(gbmonthField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(updatemonth))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(gbnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(gbmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(gbmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(gbmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updatemonth))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(gbunitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(gbbilltypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(gbserviceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(gbgstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(gbamountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(printButton))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        rightBackground.add(panel3, "card4");

        panel4.setBackground(new java.awt.Color(255, 255, 255));
        panel4.setPreferredSize(new java.awt.Dimension(640, 544));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Meter Details");

        jLabel29.setText("Meter No");

        jLabel30.setText("Meter Type");

        jLabel31.setText("Phase");

        jLabel32.setText("Region");

        jLabel33.setText("mcb rent");

        mdmeterField.setEditable(false);
        mdmeterField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mdmeterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdmeterFieldActionPerformed(evt);
            }
        });

        mdmetertypeField.setEditable(false);
        mdmetertypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdphaseField.setEditable(false);
        mdphaseField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdreigonField.setEditable(false);
        mdreigonField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mdmcbField.setEditable(false);
        mdmcbField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(46, 46, 46)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mdmeterField)
                            .addComponent(mdmetertypeField)
                            .addComponent(mdphaseField)
                            .addComponent(mdreigonField)
                            .addComponent(mdmcbField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel28)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel28)
                .addGap(32, 32, 32)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(mdmeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(mdmetertypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(mdphaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(mdreigonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(mdmcbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        rightBackground.add(panel4, "card5");

        panel5.setBackground(new java.awt.Color(255, 255, 255));
        panel5.setPreferredSize(new java.awt.Dimension(640, 544));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Payment Section");

        jButton1.setText("Pay Current Month Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel35.setText("Card No");

        jLabel36.setText("Expire Month");

        jLabel37.setText("Expire Year");

        jLabel38.setText("CVV");

        cardField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        expmntField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        expyrField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cvvField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        payamountField.setEditable(false);
        payamountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payamountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payamountFieldActionPerformed(evt);
            }
        });

        jLabel39.setText("Payable Amount");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel39))
                        .addGap(30, 30, 30)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(payamountField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(cardField)
                            .addComponent(expmntField)
                            .addComponent(expyrField)
                            .addComponent(cvvField)))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel34)
                .addGap(39, 39, 39)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(expmntField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(expyrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payamountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        rightBackground.add(panel5, "card6");

        seondCore.add(rightBackground);
        rightBackground.setBounds(300, 0, 640, 544);

        payBillButton.setBackground(new java.awt.Color(255, 255, 255));
        payBillButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payBillButton.png"))); // NOI18N
        payBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payBillButtonMouseClicked(evt);
            }
        });
        seondCore.add(payBillButton);
        payBillButton.setBounds(70, 290, 160, 30);

        myProfileButton.setBackground(new java.awt.Color(255, 255, 255));
        myProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/myProfile.png"))); // NOI18N
        myProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseClicked(evt);
            }
        });
        seondCore.add(myProfileButton);
        myProfileButton.setBounds(70, 90, 160, 30);

        currentBillButton.setBackground(new java.awt.Color(255, 255, 255));
        currentBillButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/currentBillButton'.png"))); // NOI18N
        currentBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentBillButtonMouseClicked(evt);
            }
        });
        seondCore.add(currentBillButton);
        currentBillButton.setBounds(70, 140, 160, 30);

        generateBillButton.setBackground(new java.awt.Color(255, 255, 255));
        generateBillButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/genButton.png"))); // NOI18N
        generateBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseClicked(evt);
            }
        });
        seondCore.add(generateBillButton);
        generateBillButton.setBounds(70, 190, 160, 30);

        meterdetailsButton.setBackground(new java.awt.Color(255, 255, 255));
        meterdetailsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meterdetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meterDetailButton.png"))); // NOI18N
        meterdetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterdetailsButtonMouseClicked(evt);
            }
        });
        seondCore.add(meterdetailsButton);
        meterdetailsButton.setBounds(70, 240, 160, 30);

        dashboardLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardLabel.setText("DASHBOARD");
        seondCore.add(dashboardLabel);
        dashboardLabel.setBounds(70, 20, 160, 30);

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("version 1.0");
        seondCore.add(versionLabel);
        versionLabel.setBounds(120, 450, 70, 15);

        thanksLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        thanksLabel.setForeground(new java.awt.Color(255, 255, 255));
        thanksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thanksLabel.setText("thanks for using ");
        seondCore.add(thanksLabel);
        thanksLabel.setBounds(20, 450, 100, 20);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        seondCore.add(backgroundImage);
        backgroundImage.setBounds(0, 0, 940, 544);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seondCore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seondCore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        myProfileButton.setBorder(border );
        currentBillButton.setBorder(empty);
        generateBillButton.setBorder(empty);
        meterdetailsButton.setBorder(empty);
        payBillButton.setBorder(empty);
        
        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
    }//GEN-LAST:event_myProfileButtonMouseClicked

    private void currentBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentBillButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        myProfileButton.setBorder(empty);
        currentBillButton.setBorder(border);
        generateBillButton.setBorder(empty);
        meterdetailsButton.setBorder(empty);
        payBillButton.setBorder(empty);
        
        panel1.setVisible(false);
        panel2.setVisible(true);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
    }//GEN-LAST:event_currentBillButtonMouseClicked

    private void generateBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        myProfileButton.setBorder(empty);
        currentBillButton.setBorder(empty);
        generateBillButton.setBorder(border);
        meterdetailsButton.setBorder(empty);
        payBillButton.setBorder(empty);
        
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(true);
        panel4.setVisible(false);
        panel5.setVisible(false);
    }//GEN-LAST:event_generateBillButtonMouseClicked

    private void meterdetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterdetailsButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        myProfileButton.setBorder(empty);
        currentBillButton.setBorder(empty);
        generateBillButton.setBorder(empty);
        meterdetailsButton.setBorder(border);
        payBillButton.setBorder(empty);
        
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(true);
        panel5.setVisible(false);
    }//GEN-LAST:event_meterdetailsButtonMouseClicked

    private void payBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBillButtonMouseClicked
        // TODO add your handling code here:
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        Border empty = BorderFactory.createEmptyBorder();
        myProfileButton.setBorder(empty);
        currentBillButton.setBorder(empty);
        generateBillButton.setBorder(empty);
        meterdetailsButton.setBorder(empty);
        payBillButton.setBorder(border);
        
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(true);
    }//GEN-LAST:event_payBillButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SignIn().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void cbmonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonthFieldActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        printComponenet(panel3);
     
    }//GEN-LAST:event_printButtonActionPerformed

    private void mdmeterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdmeterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdmeterFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        payment();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void payamountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payamountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payamountFieldActionPerformed

    
    public void checkifchange(){
                String jan = "January";
                Object o = gbmonthField.getSelectedItem();
                String tmpvary = o.toString();
                if (jan.equals(tmpvary))
                {
                    JOptionPane.showMessageDialog(this,"updated");
                }
                else
                {
                    String tmpmeterno;
                    String tmpmonth = tmpvary.toLowerCase();
                    String tmpunit;
                    String tmpamount;
                    String met = "";
                    connection();

                    try{
                    String sql = "select meter_number from billsbymonth where name = '"+gbnameField.getText()+"'";
                    ResultSet r = stmt.executeQuery(sql);
                    while(r.next()){
                    met = r.getString("meter_number");
                    }
                    String upsql = "select * from billsbymonth where meter_number = '"+met+"'";
                    ResultSet rs = stmt.executeQuery(upsql);

                    while(rs.next()){
                     tmpmeterno = rs.getString("meter_number");
                     Home.cbmeterNoField.setText(tmpmeterno);
                    
                     tmpamount = rs.getString(tmpmonth);
                     Home.gbamountField.setText(tmpamount);
                    }

                    String upsql2 = "select * from unitsbymonth where meter_number = '"+met+"'";
                    ResultSet rs1 = stmt.executeQuery(upsql2);

                    while(rs1.next())
                    {
                    tmpunit  = rs1.getString(tmpmonth);
                     Home.gbunitField.setText(tmpunit);
                    }
                    }


                    catch(Exception ex){

                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                    
                    
                }
                
                
    }
    private void gbmonthFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gbmonthFieldMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_gbmonthFieldMouseClicked

    private void updatemonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemonthActionPerformed
        // TODO add your handling code here:
        checkifchange();
    }//GEN-LAST:event_updatemonthActionPerformed

    private void infoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseEntered
        // TODO add your handling code here:
        versionLabel.setText("version 1.0");
    }//GEN-LAST:event_infoButtonMouseEntered

    private void infoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseExited
        // TODO add your handling code here:
         versionLabel.setText("");
    }//GEN-LAST:event_infoButtonMouseExited

    private void settingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseEntered
        // TODO add your handling code here:
        thanksLabel.setText("thanks for using");
    }//GEN-LAST:event_settingButtonMouseEntered

    private void settingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseExited
        // TODO add your handling code here:
        thanksLabel.setText("");
    }//GEN-LAST:event_settingButtonMouseExited
    
    
    public void printComponenet(Component component){
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");
        pj.setPrintable (new Printable() {    
        @Override
        public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
            return Printable.NO_SUCH_PAGE;
      }

        Graphics2D g2 = (Graphics2D) pg;
        g2.translate(pf.getImageableX(), pf.getImageableY());
        component.paint(g2);
        return Printable.PAGE_EXISTS;
                                                                 }
                                         }
                        );
        if (pj.printDialog() == false)
            return;

        try {
                pj.print();
            } 
        catch (PrinterException ex) {
        // handle exception
                }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void payment(){
        
        
        
        SignIn s= new SignIn();
        s.connection();
        try{
        String cvv = cvvField.getText();
        String card = cardField.getText();
        String sql = "select * from cards where cardno = "+card+" AND cvv = "+cvv+"";
        ResultSet rs = s.stmt.executeQuery(sql);
        if(rs.next())
        {
         payamountField.setText("");
         JOptionPane.showMessageDialog(null,"payment Successful");
         
        }
        else{
        JOptionPane.showMessageDialog(null,"payment Denied");
        //no change
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextField cardField;
    public static javax.swing.JTextField cbamountField;
    public static javax.swing.JTextField cbmeterNoField;
    public static javax.swing.JTextField cbmonthField;
    public static javax.swing.JTextField cbunitField;
    private javax.swing.JLabel currentBillButton;
    private javax.swing.JTextField cvvField;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JTextField expmntField;
    private javax.swing.JTextField expyrField;
    public static javax.swing.JTextField gbamountField;
    public static javax.swing.JTextField gbbilltypeField;
    public static javax.swing.JTextField gbgstField;
    public static javax.swing.JTextField gbmeterField;
    public static javax.swing.JTextField gbmetertypeField;
    private javax.swing.JComboBox<String> gbmonthField;
    public static javax.swing.JTextField gbnameField;
    public static javax.swing.JTextField gbserviceField;
    public static javax.swing.JTextField gbunitField;
    private javax.swing.JLabel generateBillButton;
    private javax.swing.JLabel infoButton;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoutButton;
    public static javax.swing.JTextField mdmcbField;
    public static javax.swing.JTextField mdmeterField;
    public static javax.swing.JTextField mdmetertypeField;
    public static javax.swing.JTextField mdphaseField;
    public static javax.swing.JTextField mdreigonField;
    private javax.swing.JLabel meterdetailsButton;
    public static javax.swing.JTextField mpAddField;
    public static javax.swing.JTextField mpEmailField;
    public static javax.swing.JTextField mpMeterField;
    public static javax.swing.JTextField mpMobField;
    public static javax.swing.JTextField mpNameField;
    public static javax.swing.JTextField mpStateField;
    private javax.swing.JLabel myProfileButton;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JLabel payBillButton;
    public static javax.swing.JTextField payamountField;
    private javax.swing.JButton printButton;
    private javax.swing.JPanel rightBackground;
    private javax.swing.JPanel seondCore;
    private javax.swing.JLabel settingButton;
    private javax.swing.JLabel thanksLabel;
    private javax.swing.JButton updatemonth;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
